# Generated by Django 2.0.4 on 2018-07-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataExcel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='authorityRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_by', models.CharField(max_length=100)),
                ('authority_type', models.IntegerField()),
                ('authority_name', models.CharField(max_length=100)),
            ],
        ),
    ]
