# Generated by Django 2.0.7 on 2018-07-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataExcel', '0002_authorityrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrecord',
            name='import_date',
            field=models.DateField(),
        ),
    ]
